apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-app
spec:
  replicas: 3
  template:
    metadata:
      name: nginx-pod
      labels:
        name: nginx-app
        env: dev
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.16.1
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      env: dev
      name: nginx-app
