apiVersion: v1
kind: Pod
metadata:
  name: cm-only-env-pod
  labels:
    app: cm-only-end-pod
spec:
  containers:
    - name: cm-alpine
      image: alpine:latest
      command: ["sleep","3600"]
      env:
        - name: env1
          valueFrom:
            configMapKeyRef:
              name: game-demo
              key: game.properties
        - name: env2
          value: "value2"
