apiVersion: apps/v1
kind: Deployment
metadata:
  name: patch-demo
  namespace: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: patch-demo-ctr
        image: nginx:stable
      tolerations:
      - effect: NoSchedule
        key: team
        value: developer

