---
apiVersion:v1
kind:pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    env: dev
spec:
  containers:
    - name: nginx-container
      image: nginx
      env:
        - name: DEMO_GREETING
          value: "Welcome Sakthi"
      ports:
        - containerPort: 80
---
