apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: secret-pod-container
      image: alpine
      command: ["sleep","1d"]
      env:
        - name: usernm
          valueFrom:
            secretKeyRef:
              name: secret-generic-file
              key: username
          name: password
          valueFrom:
            secretKeyRef:
              name: secret-generic-file
              key: password
      volumeMounts:
        - name: cont-secret
          mountPath: "/sakthi/secret"
          readOnly: true
        - name: sa-secret
          mountPath: "/sakthi/secret/sa"
          readOnly: true
  volumes:
    - name: cont-secret
      secret:
        secretName: dotfile-secret
    - name: sa-secret
      secret:
        secretName: secret-sa-token
