apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-aws-efs
  labels:
    env: dev
    type: aws-efs
spec:
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: static-aws-efs
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0086834e9199f5638
