apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
  labels:
    env: dev
    type: local
spec:
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Mi
  storageClassName: hostpath-vol
  hostPath:
    path: "/root/efs/hostpath-vol"

