apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-aws-efs
spec:
  selector:
    matchLabels:
      type: aws-efs
    matchExpressions:
      - {key: env, operator: In, values: [dev]}
  resources:
    requests:
      storage: 50Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: static-aws-efs

