apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-aws-efs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Mi
  storageClassName: sc-aws-efs-dynamic

