---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    app: nginx-app-rc
spec:
  replicas: 3
  template:
    metadata:
      name: nginx-pod
      labels:
        environment: dev
        app: nginx-app
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
  selector:
    environment: dev
    app: nginx-app
