apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-nginx-deploy
  namespace: nginx
rules:
  - apiGroups: [""]
    resources: ["pods","configmaps","secrets"]
    verbs: ["get","watch","list","create","update","delete"]
  - apiGroups: ["apps"]
    resources: ["deployments","replicasets"]
    verbs: ["get","watch","list","create","update","delete"]

