apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-nginx
  namespace: nginx
subjects:
  - kind: Group
    name: system:serviceAccounts
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-nginx-deploy
  apiGroup: rbac.authorization.k8s.io
