apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-aws-efs-dynamic
provisioner: efs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0086834e9199f5638
  directoryPerms: "700"
