apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: secret-pod-container
      image: alpine
      command: ["sleep","1d"]
      volumeMounts:
        - name: cont-secret
          mountPath: "/sakthi/secret"
          readOnly: true
  volumes:
    - name: cont-secret
      secret:
        secretName: dotfile-secret
